---
title: "day2sesh1"
format: html
editor: visual
---

## Day 2 Sesh 1 

```{r}
#creating expression (right hand side of equation) 
ex_1 <- expression(5*x^2)
#find deriv with deriv()
my_derivative <- deriv(ex_1, "x")
my_derivative
```

```{r}
x <- 2.8
eval(my_derivative)
```

## Alternatively 

```{r}
#create expression 
ex_2 <- expression(3.1 * x^4 - 28 * x)

#find derivative with respect to x:
D(ex_2, "x")
```

## More examples with D()

```{r}
#create and store function 
fx <- expression(x^2)
# find derivative with D() fucntion 
df_dex <- D(fx, 'x')

#return derivative 
df_dex

```

```{r}
#find slope at x = 10
x <- 10
eval(df_dex)
```

```{r}
#using D() find dg/dx given g(z) = 2z^3 - 10.5z^2 +4.1 
dgdz <- expression(2*z^3 - 10.5*z^2 + 4.1)
dg_dz <- D(dgdz, 'z')
dg_dz
```

```{r}
#find T(y)= (2y^3 + 1)^4 - 8y^3
ty <- expression((2 * y^3 +1)^4 - 8*y^3)
dt_dy <- D(ty, 'y')
dt_dy

```

##  Find slope of T(y) at a range of y vallues 

```{r}
#create a vector of y values from -0.4 to 2.0 by increments of 0.1
y <- seq(from = -0.4, to = 2, by = 0.1)
eval(dt_dy)
```
